### ISSUE TITLE
Error: Io(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })

### ISSUE THREAD

**Issue by sysmat** [Markos-Th09/cargo-make-rpm#1]
- I install `cargo install cargo-make-rpm`
- In my project  I try `cargo-make-rpm` and got error

```
 cargo-make-rpm
warning: You are creating for your current OS, not for Linux. Use --target to cross compile for a Linux target.
    Finished `release` profile [optimized] target(s) in 0.34s
Error: Io(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })
```

- my toml

```toml
[package]
description = "generate apache virtual host for users with static pages"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "users_apache_virtual_host"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = true
#opt-level = 3
opt-level = "z" # for small size

[dependencies]
askama = "0.12" # template like ninja
async-trait = "0.1" 
http = "1.1" 
reqwest = {version = "0.12", features = ["json"]} 
serde = {version = "1.0", features = ["derive"]} 
serde_json = "1.0" 
tokio = {version = "1.41", features = ["macros", "rt-multi-thread"]} 

[package.metadata.rpm]
assets = [
  #["README.md", "/usr/share/doc/README.md", "644"],
]
compression = "none"
```
